README.md
The existing link goes to a 404.
=> Update sequelizejs model definition link

lumber-update.js
Update `lumber update` error log when database is empty:
`💀  Oops, your database is empty. Please, create some tables before running Lumber update.💀`
instead of
`💀  Oops, your database is empty. Please, create some tables before running Lumber generate.💀`
`generate` => `update`
=> Fix empty schema error log

CHANGELOG.md, services/database-analyzer.js, services/dumper.js, templates/model.txt
When foreignKey are generated, if they have the same name as the alias it crash the server on start
=> [*]  Command Generate - Avoid foreignKey to conflict with relationship

CHANGELOG.md, package-lock.json, package.json
When trying to update a field in ForestAdmin that is a `TINYINT` in a MySQL DB (which is the actual MySQL type for boolean) and declared as a `boolean` in a model of the Lumber instance, we get the following error:
> Incorrect integer value: 'false' for column 'feature_1' at row 1
See: https://github.com/sequelize/sequelize/issues/10633
This is [now fixed](https://github.com/sequelize/sequelize/issues/10633#issuecomment-483786351) in [`mysql2` package](https://www.npmjs.com/package/mysql2). Since the version upgrade is minor, we can update the latest version of `mysql2` (`1.7.0`)
=> [*] Records Update - Fix `TINYINT` column update when declared as a `BOOLEAN` field in the ORM model

.gitattributes, CHANGELOG.md
Ignore assets in language detection.
Change this:
Into this:
❗️ _You can not see this change by switching to this branch! It [only works on default branch](https://github.com/github/linguist/issues/4663#issuecomment-538429590). Even after the merge, [you will have to wait](https://github.com/github/linguist/issues/4663#issuecomment-538432674) to see the change. More info in the issue I opened here: https://github.com/github/linguist/issues/4663_
=> [*] Technical - Fix Github repository language

services/dumper.js
See: https://github.com/ForestAdmin/lumber/pull/266
Adds the last version `1.7.0` in generated `package.json`. Without this additional change, [this issue](https://github.com/ForestAdmin/lumber/pull/266) would still be unresolved.
_I did not added a line in `CHANGELOG.md` since it's the same issue. It should have been in the same (merged) PR, we did not noticed it._
=> [*] Technical - Fix `mysql2` version in generated `package.json`

CHANGELOG.md, lumber-generate.js, services/prompter.js
> Lumber full options, step 1: Add  "Application port" parameter (`-p, --application-port`) to lumber generate 
- Some refactor could have been done, but I want to focus on the actual topic.
- However, I modified `requests.indexOf(option) > -1;` to `requests.includes(option)` since expressiveness in code is always better.  It does not require a separate commit IMO ; just like fixing a typo or a removing dead function.
- I tested it _manually_ (see below) with: 
- no env, no param
- env, no param
- no env, param
- env, param (param is preferred over env)
- To be unit tested, this code have to be refactored AFAIK (all code belongs to `Prompter` which is a long sync imperative function).
=> [+] Command Generate - Add  "Application port" parameter (`-p, --application-port`) to `lumber generate`

CHANGELOG.md, lumber-generate.js, services/prompter.js
See: https://github.com/ForestAdmin/lumber/pull/269 & https://github.com/ForestAdmin/lumber/pull/271. According to @arnaudbesnier suggestion, to avoid breaking changes, `--ssl` option is not a boolean, but a two value option ("true" or "false").
_I added a small fix. Previously, if the `DATABASE_SSL` had a wrong value, it crashed due to JSON parsing error. Now it just fails with a user friendly(?) message._
=> [+] Command Generate - Add  "SSL" parameter (`-S, --ssl`) to `lumber generate`

CHANGELOG.md, services/prompter.js
`lumber generate` ask for schema for MySQL install. It could be removed since it's useless, MySQL does not use schema. Source: https://stackoverflow.com/questions/11618277/difference-between-schema-database-in-mysql & https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_schema
_Issue detected during new features tests_
=> [*] Command Generate - Remove schema prompt for MySQL

.eslintrc.json, CHANGELOG.md
See: https://github.com/ForestAdmin/lumber/pull/281#discussion_r334547366
=> [*] Technical - Change `no-multiple-empty-lines` ESLint rule. Disallow two and more consecutive empty lines

.travis.yml, CHANGELOG.md
11.14 is abandonned since July 2019: https://nodejs.org/en/about/releases/. We have to ensure CI use the current LTS version to build/test Lumber.
=> [*] Continuous Integration - Change `11.14` version of `node_js` to ` lts/*` in `.travis.yml`

CHANGELOG.md, package-lock.json, package.json
It fixes one security issue displayed on github + a warning when installing locally (side effect).
=> [*] Security - Upgrade `eslint` dependency to patch vulnerabilities

CHANGELOG.md, services/column-type-getter.js, services/database-analyzer.js, services/table-foreign-keys-analyzer.js
I do not usually like PR that fixes two issues, but in this case, fixing one has revealed one other: I would have not seen the foreign key error without Sequelize replacements. So the two fix are relatives to each other. So basically:
- `field = '${foo}'` as been replaced by `field = :foo`+`{ replacements: { foo } }`
- In case there is no `dbName`, `connectionUrl` is parsed for MySQL (which is the only one who requires its own database name when analyzing foreign keys).
=> [*] Command Generate - Fix foreign key imports using connection URL with MySQL

CHANGELOG.md, services/database.js
MySQL onboarding with SSL is currently broken. AFAIK, we need to provide a certificate to make it work. BTW, MySQL connection **without SSL** seems broken too (using latest lumber versions): some users did have errors, so do I. 
An actual (temporary) solution might be to not add anything about SSL when the connection is without SSL, that's the purpose of this PR. 
@SteveBunlon To test the failure scenario, I recommend using the latest version LTS of Node with a fresh lumber install and try to connect with this kind of command: 
```
FOREST_URL="foo" lumber generate "bar" --connection-url "mysql://baz:foo@localhost:33061/bar" --ssl "false" --application-host "localhost" --application-port "3310"
```
Then to test it now works, try again with this branch.
=> [*] Command Generate - Fix MySQL connection failure without SSL

CHANGELOG.md, package.json
To avoid this warning:
```
➜  lumber git:(fix/lodash-version) ✗ npm i lodash@4.17.15 --save-exact
...
npm WARN lumber-cli@2.5.1 No repository field.
...
```
=> [*] Technical - Fix repository in `package.json`

CHANGELOG.md, services/column-type-getter.js
Some MySQL types are ignored on generation. Please test this carefully (it should not break existing types recognition).
=> [+] Field Types - Support `TIMESTAMP(n)`, `SMALLINT(n)` and `BIGINT(n)` column types (MySQL)

.travis.yml, CHANGELOG.md, package.json
We support latests 10 and 12. 14 is not ready yet, 8 is dropped in one month.
=> [+] Node version - Define supported node versions (10 and 12) in `package.json`

.eslint-bin/pre-commit-hook.js, CHANGELOG.md
This PR allows committing a file deletion.
Before that, `pre-commit-hook` linter was adding the deleted files in the `listModifiedFiles`
Here is an example of the issue. After deleting a file, the linter wanted to lint it.
=> [*] Technical - Fix linted deleted files issue

CHANGELOG.md, templates/app/forest/collection.txt
I saw this when I was editing a collection file in lumber, VS code switched to "4 spaces". All other files are indented with 2 spaces, so I just fixed it. No trello card, since it took me 2 minutes, and it's a self-initiative.
=> [*] Templates - Fix indentation (from 4 to 2 spaces) in collection files

CHANGELOG.md, services/analyzer/sequelize-tables-analyzer.js, services/dumper.js, templates/app/models/sequelize-model.hbs, test/expected/sequelize/db-analysis-output/addresses.json, test/expected/sequelize/db-analysis-output/renderings.json, test/expected/sequelize/db-analysis-output/users.json, test/expected/sequelize/dumper-output/addresses.js.expected, test/expected/sequelize/dumper-output/renderings.js.expected, test/expected/sequelize/dumper-output/users.js.expected
If the two part of an association share the same string as an alias and a foreignKeyName, sequelize will crash.
=> [*] Command Generate - Fix conflict between aliases and foreignKey names

CHANGELOG.md, services/dumper.js, templates/app/models/index.txt
@arnaudbesnier I selected you as a reviewer for the following reasons:
- We discussed about this on slack.
- You made this commit: https://github.com/ForestAdmin/forest-express-mongoose/commit/9ee264ef8e1b6ae4103311d7b06b68581558535a.
Three things as been done (because it did not work without that):
- Since the linter do not accept template-like file, I had to rename `templates/app/models/index.js` to  `templates/app/models/index.txt` (the commit can not pass without that). On a side note, the template system is currently messy: a mix of `txt` files, `js` files with invalid javascript (like this one) and handlebars code. We should improve that.
- I had to add `useUnifiedTopology: true` in connect. Without this, there is a warning: …
=> Command Generate - Ensure that generated project on MongoDB use the latest `mongoose` dependency version for security reasons

CHANGELOG.md, services/dumper.js
I added the same package version as the `forest-express` package to prevent unexpected issues (as it was the forest-express dependency that was bringing the packages to the project).
=> [*] Technical - Fix the missing dependencies in the `package.json` file of the generated project

CHANGELOG.md, services/dumper.js
`bin` path is not used anymore in Lumber generated projects. This PR removes the `bin` path generation. 
@arnaud-moncel We have seen this issue during the demo of Lumber this morning. You have to test generating a project with this branch to ensure it works. Let me know if you need any help in testing this!
=> [*] Command Generate - Do not generate obsolete `bin` path

CHANGELOG.md, package.json, services/dumper.js, test/utils-to-valid-package-name.test.js, utils/to-valid-package-name.js, yarn.lock
This fix avoids an error on project startup when project name is not allowed as a package name.
It uses the official [validate-npm-package-name](https://www.npmjs.com/package/validate-npm-package-name) created by NPM team to validate the project name. If the validation fails, it tries to transform the string to something that works (since slugify is not sufficient and I did not found a lib, I created a grumpy transformer that disallow almost everything when validation fails).
(see: https://forestadmin.slack.com/archives/GAZF5Q5RV/p1577712751015700)
I can not have created a unit test about the new created function in a `utils` directory because it's already used by tests' utils; migrating the existing system is not _that_ simple (see Slack discussion). We have to find a way to do that, but …
=> [*] Command Generate - Validate and fix the package name in `package.json` to prevent error on generated server startup

CHANGELOG.md, services/analyzer/sequelize-column-type-getter.js, test-fixtures/postgres/employees.sql, test/services/sequelize-column-type-getter.test.js
See: https://forestadmin.slack.com/archives/C0FQF9Z52/p1579162444286500
> Hi, I just tried to run `lumber generate`  as per the documentation during onboarding.   I immediately got this error
```
✓ Connecting to your database
✖ Analyzing the database
> Cannot generate your project.
> An unexpected error occurred. Please reach out for help in our Slack community or create a Github issue with following error: TypeError: this.perform is not a function
(node:9725) UnhandledPromiseRejectionWarning: TypeError: this.perform is not a function
at getTypeForArray (/home/ryan/.nvm/versions/node/v12.13.1/lib/node_modules/lumber-cli/services/analyzer/sequelize-column-type-getter.js:72:42)
at async /home/ryan/.nvm/versions/node/v12.13.1/lib/node_modules/lumber-cli/services/analyzer/sequelize-tables-anal …
```
=> [*] Command Generate - Fix error on array type generation for PostgreSQL

CHANGELOG.md, docker-compose.yml, package.json, test-utils/multiple-database-version-helper.js, yarn.lock
- Tests works locally and remotely.
- No need to downgrade password.
- `mysql2` has been updated to latest MAJOR version (2) (https://github.com/sidorares/node-mysql2/blob/master/Changelog.md)
=> [+] Command Generate - Add support for MySQL 8

CHANGELOG.md, services/dumper.js
When installing a project with a mongo project with an authSource, the `=` get encoded
I get a DATABASE_URL=mongo.....?authSource&#x3D;admin
So the server does not start
To not have an encoded DATABASE_URL
=> fix(generate): fix database url encoded in .env

services/analyzer/sequelize-column-type-getter.js
See: https://github.com/ForestAdmin/lumber/pull/430
The goal is to avoid this: https://github.com/ForestAdmin/lumber/pull/430/files#diff-0ba9ef715c22f8ab287bcf3e5eb8e25bR76
Explantation here: https://github.com/ForestAdmin/lumber/pull/424/files#r422876644 (copy/paste below)
I feel like we should try to avoid introducing cognitive complexity. The complexity was already there, you added one line, so it's not your responsibility. We also should not mix refactor and feature introduction. 
**But**, I think we could prefer a refactoring task over adding `eslint-disable-next-line`. WDYT?
A small refactor could be replacing all these occurrence (they are considered as "complex" by the linter, we could consider these as duplicate):
```js
case type.match(/^SMALLINT.*/i) || {}).input:
```
With: …
=> refactor: reduce sequelize-column-type-getter code complexity

services/analyzer/sequelize-tables-analyzer.js, services/dumper.js, test-expected/sequelize/dumper-output/users.expected.js, test-fixtures/mssql/sample_table.sql, test-fixtures/mssql/underscored_no_fields.sql, test-fixtures/mysql/sample_table.sql, test-fixtures/mysql/underscored_no_fields.sql, test-fixtures/postgres/sample_table.sql, test-fixtures/postgres/underscored_no_fields.sql, test/services/database-analyzer/database-analyzer-sequelize.test.js
Fixes [#4embh7](https://app.clickup.com/t/4embh7).
This PR contains to bug fixes in order to correctly handle snake_cased tables that only contain foreign keys.
The issue came from two different bugs in the code :
- The `through` property that is generated when having `belongsToMany` relationships was using the table name as its value, but it's meant to contain the name of the model, which is camelCased in our setup.
- The `options.underscored` property was only computed from the fields names, so if you had no fields but had some snake_cased FKs, it still defaulted to false.
The consequence was that in the schema building step, after having generated your project, Sequelize couldn't find the snake_cased model in the `through` property, and as such created it on its own (which is its …
=> fix: model generation inconsistencies

services/analyzer/sequelize-tables-analyzer.js, services/dumper.js, templates/app/models/sequelize-model.hbs, test-expected/sequelize/db-analysis-output/users.expected.json
According to https://sequelize.org/master/manual/advanced-many-to-many.html
```
By passing a string to through above, we are asking Sequelize to automatically generate a model named User_Profiles as the through table (also known as junction table), with only two columns: userId and profileId. A composite unique key will be established on these two columns.
```
=> refactor: refactor through model name with hasMany relationships

package-lock.json, package.json, services/dumper.js, templates/app/app.hbs
Linked to CU-6gmxhz
This PR introduces a new dependency `forest-express` which was previously implied on generated projects by `forest-express-{mongodb|sequelize}`.
The generated `app.js` file now uses the `errorHandler`, exposed by `forest-express` (see https://github.com/ForestAdmin/forest-express/pull/462), to be sure that error are correctly serialized.
=> fix: :bug: generate agents that return JSON errors

services/dumper.js, test-expected/sequelize/db-analysis-output/default-values.expected.js, test-expected/sequelize/dumper-output/default-values.expected.js
Some "NULL" where included in models without quoting due to non-string type for database fields.
eg: DB column type `numeric(12,2)` and default value `NULL::numeric`.
Linked to: CU-78nvya
=> fix(models): enforce string type for default value when 'NULL'

services/database.js, templates/app/env.hbs, templates/app/models/index.hbs, test-expected/sequelize/dumper-output/env.expected, test-expected/sequelize/dumper-output/index.expected.js, test/services/dumper/dumper-sequelize.test.js
As suggested by @arnaudbesnier, we do not add a `dialectOptions` option. See two dead PRs here: #471 & #468 
Let's add `DATABASE_REJECT_UNAUTHORIZED=false` every time, for each case. It solves P1 and it doesn't try to solve problems that don't exist.
See: 
- https://github.com/ForestAdmin/lumber/issues/452
- https://app.clickup.com/t/82nzna
- https://community.forestadmin.com/t/ssl-issues-with-forestadmin/837
- https://forestadmin.productboard.com/roadmap/1782065-roadmap-forest-by-lanes/features/5553384/insights
- https://forestadmin.slack.com/archives/GCYMMU085/p1599721557051000
=> feat: trust SSL certificate by default to ease users onboarding

templates/app/app.hbs
When an AJAX call is redirected to another endpoint, the origin is set to the string `'null'` instead of the original origin. Servers have to explicitly allow this value and return `null` in the corresponding cors header.
As we are preparing the authentication flow with OIDC, we will need to allow this origin, at least for authentication routes.
I did not find an easy way to let `forest-express` handle these cors declarations and only accept this value for routes that needed it. So the simpler solution is to allow `null` for all routes.
=> feat: allow calls from redirections

test-utils/mongo-helper.js
Running the tests _twice_ could lead to this obscure error when `system` tables has been created:
```
MongoError: ns not found
```
In this [PR](https://github.com/ForestAdmin/lumber/pull/485), I created a test on a view: a view automatically creates a system table. This table cannot be dropped, so it has to be ignored (it crashes when you run test twice if you do not ignore it). With this fix, you can run the test ∞ times.
=> test: avoid dropAllCollections error when having system tables

services/analyzer/mongo-collections-analyzer.js, services/analyzer/mongo-hasmany-analyzer.js, services/analyzer/mongo-references-analyzer.js, test-expected/mongo/db-analysis-output/complex-model-with-a-view.expected.json, test/services/database-analyzer/database-analyzer-mongo.test.js, utils/mongo-collections.js
This fix is based on Sébastien's suggestion. We have to remove "system" collections every time we use `databaseConnection.collections()`.
👉  To do so, I had to refactor some code to avoid duplicating too much things. @ reviewer, we try to avoid mixing refactoring and a fix. For this particular case, fixing it without refactoring would have resulted maybe in more code than this actual commit. That's why I exceptionally decided to mix refactor and a fix. Feel free to criticize. Also, code climate ask me for **more** refactor in this PR, I will not follow its advice: since `detectReference ` uses sub-functions that are actually different in each files. It would have required too much work to refactor it.
Sébastien gave me a sample database that is available in the click-up ticket. This …
=> fix: generate command could fail when analysing relations on MongoDB when having one or more views

package.json, services/dumper.js, yarn.lock
Please note there is a docker image which is a turnkey to have MySQL last version with data: 
`docker run -p 9000:3306 forestadmin/turnkey-mysql:1.0.1`
There is also a turnkey for 'low' version of musql:
`docker run -p 9001:3306 forestadmin/turnkey-mysql-old:1.0.0`
passwords are forest/secret for both, database is "turnkey"
=> fix: update mysql driver version

.travis.yml
See: https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry. We will not be pushing docker images from here, but the login step is still valid. According to docker new terms of pull limit (https://www.docker.com/increase-rate-limits#:~:text=Anonymous%20and%20Free%20Docker%20Hub,%3A%20toomanyrequests%3A%20Too%20Many%20Requests.&text=You%20have%20reached%20your%20pull%20rate%20limit) this should be enough to double our pull capacity (200 pulls/6h)
=> chore(docker): add dockerhub login step in ci

README.md, lumber-generate.js, lumber-update.js
=> feat: add deprecation warning to use forest cli instead
