README.md

Title says all
cc @SeyZ, @moflo

fixes syntax highlighting for README

---

CHANGELOG.md
services/table-analyzer.js

Fixes: https://github.com/ForestAdmin/lumber/issues/84

[+] Field Types - Support TIMESTAMP column type (MySQL)

---

CHANGELOG.md
lumber-generate.js
package.json
services/authenticator.js
services/dumper.js
templates/app/env

Fixes #21
Fixes #142 (The other PRr doesn't fix the problem)

[*] Generate - Fixing port and authentication

---

CHANGELOG.md
lumber-generate.js
services/authenticator.js
templates/app/bin/www

Linked to: https://github.com/ForestAdmin/forestadmin-server/pull/709

[-] Improvement - Reduce the number of http requests to init the project

---

CHANGELOG.md
templates/app/env

This reverts commit 4bcb04273dd81174268dc886e7db12f751ccbb15.

Revert "[*] Technical - Add `FOREST_URL` for easier development"

---

services/table-analyzer.js

I came across with #52, but still float types were not taken into account.
I've made this very quick and haven't read through all the code, nor test, etc.
Let me know if I should add something else, like changelog or anything.

table-analyzer: add support for FLOAT types

---

lumber-install.js
lumber-update.js

* This pull request adds support for a custom schema for the install and update lumber scripts

Add support for custom database schema

---

CHANGELOG.md
package-lock.json
package.json

Step 2 (see [this issue](https://github.com/ForestAdmin/lumber/pull/268) for step 1).

[-] Dependencies - Remove obsolete `mysql` dependency

---

CHANGELOG.md
lumber-generate.js
services/prompter.js

~~Waiting for #269 to be reviewed.~~

[+] Command Generate - Add "Application host" parameter (`-H, --application-host`) to `lumber generate`

---

CHANGELOG.md
lumber-install.js

See: https://github.com/ForestAdmin/lumber-forestadmin/pull/10 (params are handled by _ForestAdmin/lumber-forestadmin_)

[+] Command generate - Add parameters documentation to `lumber install`

---

CHANGELOG.md
lumber-generate.js
lumber-install.js
services/database-analyzer.js
services/environment-checker.js
services/migrator.js
services/prompter.js

Full PR including #260 (thanks to @VincentMolinie :wave:), #269, #271, #273, #276. @arnaudbesnier Final step, everything was already reviewed inside. Still it may require one last review :)

[-] Command Generate - Migrate all options from environment variables to command parameters

---

CHANGELOG.md
services/database-analyzer.js

[*] Command Generate - Fixed error when analyzing MongoDB views

---

CHANGELOG.md
Dockerfile

See: https://github.com/ForestAdmin/lumber-forestadmin/pull/14

[-] Use lumber options in `Dockerfile`

---

CHANGELOG.md
package-lock.json
package.json

https://stackoverflow.com/questions/53266471/saslprep-warning-when-using-mongoclient-connect/57234317#57234317

[+] MongoDB - Enhance authentication mechanism using optional `salsprep` library

---

CHANGELOG.md
lumber-login.js
services/authenticator.js
services/prompter.js
utils/authenticator-helper.js
utils/regexs.js

As you mentioned here: https://github.com/ForestAdmin/lumber/pull/295, the login has regressed. The purpose of this PR is to implement the same behaviour as before and adding the new parameters

[*] Command Login - Fix login to match old behaviour

---

.npmignore
CHANGELOG.md

Test with `npm publish  --dry-run` ([TIL](https://docs.npmjs.com/cli/publish))

[*] Git hooks - Remove git hooks from npm package (fix installation issue on Windows)

---

package.json
services/table-foreign-keys-analyzer.js
test/expected/sql/foreign-keys-analysis-output/addresses.js
test/expected/sql/foreign-keys-analysis-output/customers.js
test/expected/sql/foreign-keys-analysis-output/reviews.js
test/fixtures/mysql/reviews.sql
test/services/table-foreign-keys-analyzer.js

Add detection of hasMany, hasOne and belongsToMany toSQL databases.
Add Mysql script and expected output.

[+] Lumber - Generate SQL hasMany, hasOne and BelongsToMany - MySQL Script

---

CHANGELOG.md
services/dumper.js

Generate files in alphabetical order (directories first)

[*] Command Generate - Generate files in alphabetical order

---

services/dumper.js
templates/app/models/index.hbs

For this PR I would suggest to not change the changelog, and to squash the present work with this one : https://github.com/ForestAdmin/lumber/pull/386
As the subjects are related and next to each other in the git history, It would be much cleaner and tinier.

[-] Models - Improve models exports to support model addition / deletion without requiring changes.

---

CHANGELOG.md
services/dumper.js
templates/app/models/mongo-model.hbs
templates/app/models/sequelize-model.hbs
templates/app/routes/route.hbs
utils/strings.js

Fix error on project generation with database contain table with number as name.

[*] Command generate - Fix project generation on table with number as name

---

CHANGELOG.md
templates/app/routes/route.hbs

This PR has to be merged and released when:
-  [x] **AND** `forest-express-sequelize` updates its `forest-express` dependency to v6
-  [x] **AND** `forest-express-sequelize` is released (new major: 6)
-  [x] **AND** `forest-express-mongoose` updates its `forest-express` dependency to v6
-  [x] **AND** `forest-express-mongoose` is released (new major: 6)
-  [ ] ~~**AND** this PR is updated to use `forest-express-sequelize` and `forest-express-mongoose` in v6.~~ **(EDIT: see: https://github.com/ForestAdmin/lumber/pull/405)**

[+] Command Generate - Add "delete a list of …" in generated route file

---

CHANGELOG.md
README.md

Fix images links in lumber README

chore(links): update picture links

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

See: https://github.com/ForestAdmin/lumber/pull/414

chore(collaboration): add a pull requests template

---

.travis.yml
CHANGELOG.md

ci: remove configuration warnings

---

CHANGELOG.md
test/utils/to-valid-package-name.test.js

refactor(tests): move `to-valid-package-name` test to correct folder

---

CHANGELOG.md
services/dumper.js
templates/app/docker-compose.hbs
test/services/dumper/dumper.test.js

Initiale PR --> https://github.com/ForestAdmin/lumber/pull/422

fix(generate): default configuration now works for users using Linux and a local database

---

.gitignore
CHANGELOG.md
package.json
services/analyzer/mysql-table-constraints-getter.js
services/analyzer/sequelize-column-type-getter.js
services/analyzer/sequelize-table-constraints-getter.js
services/analyzer/sequelize-tables-analyzer.js
yarn.lock

Need to wait a new release of Sequelize to fix `queryInterface.describeTable` function.
[Clickup card](https://app.clickup.com/t/4ur8wt)

fix(command generate): fix error when analyzing database on mssql with case sensitive collation

---

services/analyzer/sequelize-column-type-getter.js
test-fixtures/mssql/json.sql
test-fixtures/mysql/json.sql
test-fixtures/postgres/json.sql
test/services/sequelize-column-type-getter.test.js

Initiale PR --> https://github.com/ForestAdmin/lumber/pull/424

feat(command-generate): support 'JSON' field type on installation

---

package.json

Fixes [#46f87a](https://app.clickup.com/t/46f78a).

chore: update sequelize

---

yarn.lock

chore: update yarn lock file (fix broken ci)

---

package.json
yarn.lock

fix(command generate): fix generation of project with postgres on node 14.4

---

services/dumper.js

fix(dumper): fix issue where project using nodejs v14 could never connect to postgres database

---

utils/messages.js

fix: suggest to reach help in the discourse community instead of Slack

---

.eslint-bin/pre-commit-hook.js

chore: fix the pre-commit hook with renamed files

---

services/dumper.js

chore(generate): add missing project dependency declaration

---

templates/app/app.hbs
templates/app/middlewares/forestadmin.hbs
templates/app/middlewares/welcome.hbs
templates/app/models/index.hbs
templates/app/server.hbs

chore(generate): generate projects with a more consistent JavaScript syntax

---

docker-compose.yml

fix: postgres 12.2 support

---

services/analyzer/sequelize-tables-analyzer.js
templates/app/models/sequelize-model.hbs
test-expected/sequelize/db-analysis-output/addresses.expected.json
test-expected/sequelize/db-analysis-output/customers.expected.json
test-expected/sequelize/db-analysis-output/rentals.expected.json
test-expected/sequelize/db-analysis-output/users.expected.json
test-expected/sequelize/dumper-output/addresses.expected.js
test-expected/sequelize/dumper-output/customers.expected.js
test-expected/sequelize/dumper-output/users.expected.js

fix(generate): handle NOT NULL constraint

---

services/analyzer/sequelize-tables-analyzer.js
templates/app/models/sequelize-model.hbs
test-expected/sequelize/db-analysis-output/users.expected.json
test-expected/sequelize/dumper-output/users.expected.js

This helps with some rare cases where associations aliases were duplicated.
Linked to: CU-78nvya

fix(models): add missing association aliases

---

templates/app/models/index.hbs
test-expected/sequelize/dumper-output/index.expected.js

Woops. See: https://github.com/ForestAdmin/lumber/issues/452#issuecomment-697213142

fix: fix rejectUnauthorized handling

---

services/analyzer/mongo-collections-analyzer.js
services/analyzer/mongo-embedded-analyzer.js
test/services/database-analyzer/database-analyzer-mongo.test.js
test/services/database-analyzer/database-analyzer-sequelize.test.js
utils/mongo-primitive-type.js

test(coverage): fix coverage computation

---

.travis.yml
package.json

test(coverage): transmit coverage to Code Climate

---

README.md

doc: update qonto website url

---

services/dumper.js
templates/app/Dockerfile.hbs
templates/app/docker-compose.hbs
templates/app/env.hbs

It seems it works. **Not tested on Linux though**. See: https://github.com/ForestAdmin/lumber/issues/439

feat(security): use env variables in docker-compose.yml

---

package.json

chore: fix the ci by supporting all node versions >= 10

---

services/logger.js

Clears the console when running tests, improves readability of the tests logs

improvement: don't log messages during tests

---

templates/app/app.hbs

Fix: https://github.com/ForestAdmin/forestadmin/pull/2614

chore(cors): modify cors middleware order for avoiding json parsing issue with xhr

---

services/dumper.js
templates/app/config/databases.hbs
templates/app/databases.config.hbs
templates/app/models/index.hbs
test-expected/mongo/dumper-output/databases.config.expected.js
test-expected/mongo/dumper-output/index.expected.js
test-expected/sequelize/dumper-output/databases.config.expected.js
test-expected/sequelize/dumper-output/index.expected.js
test/services/dumper/dumper-mongo.test.js
test/services/dumper/dumper-sequelize.test.js
test/services/dumper/dumper-sql.test.js

chore: add databases config file

---

services/dumper.js

Needed to fix a bug with setting authentication cookies (will be used with OIDC).

chore: bump express version in generated projects

---

services/analyzer/sequelize-column-type-getter.js
test-expected/sequelize/db-analysis-output/rentals.expected.json
test-fixtures/mssql/books.sql
test-fixtures/mssql/customers.sql
test-fixtures/mssql/reviews.sql
test-fixtures/mssql/user_books.sql
test-fixtures/mssql/users.sql
test-fixtures/mysql/books.sql
test-fixtures/mysql/customers.sql
test-fixtures/mysql/reviews.sql
test-fixtures/mysql/user_books.sql
test-fixtures/mysql/users.sql

fix(models): properly set type for date only fields

---

package.json
yarn.lock

chore: facilitate the development of tests by adding jest types

---

context/application-context.js
context/index.js
context/init.js
lumber.js
test/context/application-context.test.js

refactor: add dependency injection, to allow unit testing classes

---

services/dumper.js
templates/app/app.hbs

⚠️ Wait for the release of https://github.com/ForestAdmin/forest-express-sequelize/pull/552 & https://github.com/ForestAdmin/forest-express-mongoose/pull/443 before merging this

fix: remove forest-express dependency in generated package.json

---

package.json
yarn.lock

chore: remove node 14 warning by updating mongodb dependency

---

services/analyzer/sequelize-column-type-getter.js

The original issue is reproductible using this database on `master`: `docker run -p 9001:3306 forestadmin/turnkey-mysql-old:1.0.0`, and should be fixed with this contribution.
Manually tested on my end using mysql 5.6 & 5.7. See https://github.com/ForestAdmin/lumber/pull/501#pullrequestreview-539186649 for further details.

fix: handle medium int column type

---

context/index.js
context/init.js
lumber-login.js
package.json
services/oidc/authenticator.js
services/oidc/error-handler.js
services/oidc/error.js
test/context/application-context.test.js
test/services/oidc/authenticator.test.js
test/services/oidc/error-handler.test.js
utils/terminator.js
yarn.lock

feat(authentication): allow to login using OpenId, without entering a password

---

context/init.js
lumber-login.js
services/error-handler.js
services/oidc/error.js
test/services/error-handler.unit.test.js
test/services/oidc/authenticator.test.js
utils/errors.js
utils/lumber-error.js

Allows to use the error handler in a more generic way. I need this refactoring for the next updates.

refactor: use the error handle for all types of application errors

---

context/init.js
deserializers/application-token.js
lumber-login.js
serializers/application-token.js
services/api.js
services/application-token.js
services/authenticator.js
services/project-creator.js
test/deserializers/application-token.unit.test.js
test/serializers/application-token.unit.test.js
test/services/api.unit.test.js
test/services/application-token.unit.test.js
utils/errors/application-token/unable-to-create-application-token-error.js

feat(authentication): create an applicationt token when logging in

---

services/analyzer/sequelize-tables-analyzer.js

refactor: remove globally defined sequelize variables from sequelize-tables-analyzer

---

jest.config.js

chore: fix coverage collection

---

services/dumper.js
test/services/dumper/dumper-mongo.test.js
test/services/dumper/dumper-sequelize.test.js
test/services/dumper/dumper-sql.test.js
test/services/dumper/dumper.test.js

refactor: switch dumper to class

---

services/analyzer/database-analyzer.js
services/analyzer/mongo-collections-analyzer.js
services/analyzer/sequelize-tables-analyzer.js
test/services/analyzer/mongo-collections-analyzer.test.js
test/services/analyzer/sequelize-tables-analyzer.test.js
test/utils/errors.test.js
utils/errors.js

refactor(errors): refactor utils error

---

test/context/init.test.js

test: add context init test

---

context/init.js
lumber-generate.js
services/database.js
test/services/database.unit.test.js

refactor(database): switched database to class with injection

---

context/init.js
lumber-generate.js
lumber-login.js
lumber-logout.js
services/api.js
services/authenticator.js
services/project-creator.js
test/context/application-context.test.js

refactor: allow to unit-test the authenticator service

---

context/init.js
lumber-login.js
services/api.js
services/application-token.js
services/authenticator.js
services/project-creator.js
test/services/api.unit.test.js
test/services/application-token.unit.test.js
test/services/authenticator.unit.test.js

feat: invalidate the application token on logout

---

.travis.yml

chore: allow to release beta versions

---

.travis.yml

chore: allow to release beta versions (#521)

---

package.json
services/dumper.js
yarn.lock

refactor(dumper): update mkdirp to 1.0.4 to remove bluebird dependency in dumper

---

context/init.js
lumber-generate.js
services/dumper.js
test/services/dumper/dumper-mongo.test.js
test/services/dumper/dumper-sequelize.test.js
test/services/dumper/dumper-sql.test.js
test/services/dumper/dumper.test.js
test/services/dumper/dumper.unit.test.js
utils/strings.js

refactor(dumper): refactor dumper to use dependency injection

---

test/services/dumper/dumper-sequelize.test.js

test(dumper): fix failing test on dumper

---

context/init.js
services/dumper.js
test/services/dumper/dumper.test.js
test/services/dumper/dumper.unit.test.js

fix: incorrect FOREST_URL generated in docker-compose.yml

---

lumber-update.js
services/database.js
services/dumper.js
test/services/database.unit.test.js
test/services/dumper/dumper.unit.test.js

chore: add more error on lumber update

---

lumber-update.js
services/database.js
test/services/database.unit.test.js

fix(update): fix minor inconsistencies in lumber update command

---

lumber-update.js
services/dumper.js
test/services/dumper/dumper.unit.test.js

fix(update): fix modelsDir not used by lumber update

---

test/services/dumper/dumper-sequelize.test.js

fix: fix tests for handle foreign key toward non primary key

---

templates/app/routes/route.hbs
test-expected/sequelize/dumper-output/export.expected.route.js

fix(view-list): fix bad records count in view list if the record details access is forbidden

---

.github/workflows/build.yml

chore(release): fix npm release with the new CI

---

services/dumper.js

chore: merge master

---

templates/app/models/index.hbs
test-expected/mongo/dumper-output/index.expected.js

fix: fix models import error on mongo model index

---

templates/app/app.hbs

feat(context): accept all headers to transmit forest context url in each data request

---

templates/app/docker-compose.hbs

fix: include APPLICATION_URL into the autogenerated docker-compose.yml file

---

yarn.lock

fix(security): patch axios dependency vulnerabilities

---

package.json
yarn.lock

fix(security): patch node-notifier dependency vulnerabilities

---

yarn.lock

fix(security): patch xmldom dependency vulnerabilities

---

services/dumper.js
templates/app/app.hbs

fix: express-jwt vulnerability

---

services/dumper.js
test/services/dumper/dumper.unit.test.js

fix: fix liana version check for lumber update command
